name: Build release archive

on:
  push:
    branches:
      - 'chore/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dir
        run: |
          mkdir temp

      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          php_extensions: pdo_mysql pdo_sqlite pdo_pgsql gettext
          dev: no
          args: "--prefer-dist"
          command: create-project
          working_dir: "temp/"

